import type {Metadata} from "next";
import "./globals.css";
import {ClashGreek, epilogue, Helvetica, raleway} from "../../public/font/fontsConfig";
import {ToastContainer} from "./Toaster/ToastContainer"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={` ${epilogue.className} ${raleway.variable} ${Helvetica.variable} ${ClashGreek.variable} antialiased`}
        >
        <ToastContainer>
            {children}
        </ToastContainer>
        </body>
        </html>
    );
}
